package io.github.trueruslan.zakupgotov.comparison;

public enum RetailerComparisonReason {
    COVERAGE_DISCOVERY,
    COVERAGE_DEGRADED,
    COVERAGE_BLOCKED,
    PRODUCTION_ACCESS_PENDING,
    PRODUCTION_ACCESS_BLOCKED,
    DATA_NOT_AVAILABLE,
    SOURCE_UNAVAILABLE,
    ITEM_UNMATCHED,
    ITEM_AMBIGUOUS,
    ITEM_UNAVAILABLE,
    PACKAGE_QUANTITY_UNKNOWN,
    QUANTITY_UNIT_MISMATCH,
    AVAILABILITY_UNKNOWN
}
