/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product API availability information */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retailers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get canonical retailer coverage and comparison readiness */
        get: operations["getRetailerReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparison-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient locality-based basket comparison preview */
        post: operations["createComparisonPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemInfo: {
            /** @constant */
            name: "zakup-gotov-api";
            /** @enum {string} */
            status: "UP";
        };
        RetailerReadinessResponse: {
            retailers: components["schemas"]["RetailerReadinessItem"][];
        };
        RetailerReadinessItem: {
            id: components["schemas"]["RetailerId"];
            displayName: string;
            coverage: components["schemas"]["RetailerCoverageStatus"];
            productionAccess: components["schemas"]["RetailerProductionAccessStatus"];
            comparisonStatus: components["schemas"]["RetailerComparisonStatus"];
            reasons: components["schemas"]["RetailerComparisonReason"][];
            total?: components["schemas"]["BasketTotal"];
            freshness?: components["schemas"]["RetailerFreshness"];
        };
        ComparisonPreviewRequest: {
            locality: string;
            items: components["schemas"]["ComparisonPreviewRequestItem"][];
        };
        ComparisonPreviewRequestItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["ComparisonPreviewQuantityInput"];
        };
        ComparisonPreviewQuantityInput: {
            amount: number;
            unit: components["schemas"]["QuantityInputUnit"];
        };
        /** @enum {string} */
        QuantityInputUnit: "PIECE" | "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER";
        CanonicalQuantity: {
            amount: number;
            unit: components["schemas"]["CanonicalQuantityUnit"];
        };
        /** @enum {string} */
        CanonicalQuantityUnit: "PIECE" | "GRAM" | "MILLILITER";
        ComparisonPreviewResponse: {
            locality: string;
            items: components["schemas"]["ComparisonPreviewRequestedItem"][];
            retailers: components["schemas"]["ComparisonPreviewRetailer"][];
        };
        ComparisonPreviewRequestedItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
        };
        ComparisonPreviewRetailer: {
            id: components["schemas"]["RetailerId"];
            displayName: string;
            coverage: components["schemas"]["RetailerCoverageStatus"];
            productionAccess: components["schemas"]["RetailerProductionAccessStatus"];
            comparisonStatus: components["schemas"]["RetailerComparisonStatus"];
            reasons: components["schemas"]["RetailerComparisonReason"][];
            total?: components["schemas"]["BasketTotal"];
            freshness?: components["schemas"]["RetailerFreshness"];
            items: components["schemas"]["ComparisonPreviewItem"][];
        };
        ComparisonPreviewItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            requestedQuantity: components["schemas"]["CanonicalQuantity"];
            status: components["schemas"]["BasketItemResolutionStatus"];
            candidateProductNames: string[];
            selection?: components["schemas"]["ComparisonPreviewSelection"];
        };
        ComparisonPreviewSelection: {
            productName: string;
            packageQuantity: components["schemas"]["CanonicalQuantity"];
            packageCount: number;
            coveredQuantity: components["schemas"]["CanonicalQuantity"];
            lineTotal: number;
            currencyCode: string;
        };
        /** @enum {string} */
        BasketItemResolutionStatus: "FULFILLED" | "AVAILABILITY_UNKNOWN" | "UNMATCHED" | "AMBIGUOUS" | "UNAVAILABLE" | "PACKAGE_QUANTITY_UNKNOWN" | "QUANTITY_UNIT_MISMATCH";
        InvalidComparisonPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-comparison-preview";
            /** @constant */
            title: "Invalid comparison preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_COMPARISON_PREVIEW";
            errors: components["schemas"]["ComparisonPreviewValidationError"][];
        };
        ComparisonPreviewValidationError: {
            field: string;
            message: string;
        };
        /** @enum {string} */
        RetailerId: "pyaterochka" | "perekrestok" | "chizhik" | "magnit" | "lenta" | "vkusvill" | "ozon-fresh" | "samokat";
        /** @enum {string} */
        RetailerCoverageStatus: "CONNECTED" | "DISCOVERY" | "DEGRADED" | "BLOCKED";
        /** @enum {string} */
        RetailerProductionAccessStatus: "READY" | "PENDING" | "BLOCKED";
        /** @enum {string} */
        RetailerComparisonStatus: "READY" | "UNCERTAIN" | "INCOMPLETE" | "UNAVAILABLE";
        /** @enum {string} */
        RetailerComparisonReason: "COVERAGE_DISCOVERY" | "COVERAGE_DEGRADED" | "COVERAGE_BLOCKED" | "PRODUCTION_ACCESS_PENDING" | "PRODUCTION_ACCESS_BLOCKED" | "DATA_NOT_AVAILABLE" | "SOURCE_UNAVAILABLE" | "ITEM_UNMATCHED" | "ITEM_AMBIGUOUS" | "ITEM_UNAVAILABLE" | "PACKAGE_QUANTITY_UNKNOWN" | "QUANTITY_UNIT_MISMATCH" | "AVAILABILITY_UNKNOWN";
        BasketTotal: {
            amount: number;
            currencyCode: string;
        };
        RetailerFreshness: {
            basis: components["schemas"]["RetailerFreshnessBasis"];
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            providerUpdatedAt?: string;
        };
        /** @enum {string} */
        RetailerFreshnessBasis: "OBSERVATION_ONLY" | "PROVIDER_TIMESTAMP";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API availability information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    getRetailerReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical retailer readiness information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerReadinessResponse"];
                };
            };
        };
    };
    createComparisonPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonPreviewRequest"];
            };
        };
        responses: {
            /** @description Product-safe comparison preview for all canonical retailers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonPreviewResponse"];
                };
            };
            /** @description Invalid comparison preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidComparisonPreviewProblem"];
                };
            };
        };
    };
}
