/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product API availability information */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retailers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get canonical retailer coverage and comparison readiness */
        get: operations["getRetailerReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparison-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient locality-based basket comparison preview */
        post: operations["createComparisonPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipe-shopping-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert a transient recipe request into a canonical shopping-list preview */
        post: operations["createRecipeShoppingPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipe-comparison-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient recipe-to-retailer comparison preview */
        post: operations["createRecipeComparisonPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-plan-shopping-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient weekly-plan shopping-list preview */
        post: operations["createWeeklyPlanShoppingPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-plan-pantry-shopping-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient Pantry-aware weekly-plan shopping preview */
        post: operations["createWeeklyPlanPantryShoppingPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-plan-comparison-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a transient weekly-plan-to-retailer comparison preview */
        post: operations["createWeeklyPlanComparisonPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemInfo: {
            /** @constant */
            name: "zakup-gotov-api";
            /** @enum {string} */
            status: "UP";
        };
        RetailerReadinessResponse: {
            retailers: components["schemas"]["RetailerReadinessItem"][];
        };
        RetailerReadinessItem: {
            id: components["schemas"]["RetailerId"];
            displayName: string;
            coverage: components["schemas"]["RetailerCoverageStatus"];
            productionAccess: components["schemas"]["RetailerProductionAccessStatus"];
            comparisonStatus: components["schemas"]["RetailerComparisonStatus"];
            reasons: components["schemas"]["RetailerComparisonReason"][];
            total?: components["schemas"]["BasketTotal"];
            freshness?: components["schemas"]["RetailerFreshness"];
        };
        ComparisonPreviewRequest: {
            locality: string;
            items: components["schemas"]["ComparisonPreviewRequestItem"][];
        };
        ComparisonPreviewRequestItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["ComparisonPreviewQuantityInput"];
        };
        ComparisonPreviewQuantityInput: {
            amount: number;
            unit: components["schemas"]["QuantityInputUnit"];
        };
        RecipeShoppingPreviewRequest: {
            title: string;
            baseServings: number;
            targetServings: number;
            ingredients: components["schemas"]["RecipeShoppingPreviewIngredientInput"][];
        };
        RecipeShoppingPreviewIngredientInput: {
            requirement: string;
            quantity: {
                amount: number;
                unit: components["schemas"]["QuantityInputUnit"];
            };
        };
        RecipeComparisonPreviewRequest: {
            locality: string;
            recipe: components["schemas"]["RecipeShoppingPreviewRequest"];
        };
        WeeklyPlanComparisonPreviewRequest: {
            locality: string;
            weeklyPlan: components["schemas"]["WeeklyPlanShoppingPreviewRequest"];
        };
        /** @enum {string} */
        QuantityInputUnit: "PIECE" | "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER";
        CanonicalQuantity: {
            amount: number;
            unit: components["schemas"]["CanonicalQuantityUnit"];
        };
        /** @enum {string} */
        CanonicalQuantityUnit: "PIECE" | "GRAM" | "MILLILITER";
        RecipeShoppingPreviewResponse: {
            recipe: components["schemas"]["RecipeShoppingPreviewRecipe"];
            shoppingList: components["schemas"]["RecipeShoppingPreviewShoppingList"];
        };
        RecipeComparisonPreviewResponse: {
            recipeShoppingPreview: components["schemas"]["RecipeShoppingPreviewResponse"];
            comparisonPreview: components["schemas"]["ComparisonPreviewResponse"];
        };
        RecipeShoppingPreviewRecipe: {
            /** Format: uuid */
            id: string;
            title: string;
            baseServings: number;
            targetServings: number;
            ingredients: components["schemas"]["RecipeShoppingPreviewRecipeIngredient"][];
        };
        RecipeShoppingPreviewRecipeIngredient: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
        };
        RecipeShoppingPreviewShoppingList: {
            /** Format: uuid */
            id: string;
            items: components["schemas"]["RecipeShoppingPreviewShoppingItem"][];
        };
        RecipeShoppingPreviewShoppingItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
            sourceIngredientIds: string[];
        };
        ComparisonPreviewResponse: {
            locality: string;
            items: components["schemas"]["ComparisonPreviewRequestedItem"][];
            retailers: components["schemas"]["ComparisonPreviewRetailer"][];
        };
        ComparisonPreviewRequestedItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
        };
        ComparisonPreviewRetailer: {
            id: components["schemas"]["RetailerId"];
            displayName: string;
            coverage: components["schemas"]["RetailerCoverageStatus"];
            productionAccess: components["schemas"]["RetailerProductionAccessStatus"];
            comparisonStatus: components["schemas"]["RetailerComparisonStatus"];
            reasons: components["schemas"]["RetailerComparisonReason"][];
            total?: components["schemas"]["BasketTotal"];
            freshness?: components["schemas"]["RetailerFreshness"];
            items: components["schemas"]["ComparisonPreviewItem"][];
        };
        ComparisonPreviewItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            requestedQuantity: components["schemas"]["CanonicalQuantity"];
            status: components["schemas"]["BasketItemResolutionStatus"];
            candidateProductNames: string[];
            selection?: components["schemas"]["ComparisonPreviewSelection"];
        };
        ComparisonPreviewSelection: {
            productName: string;
            packageQuantity: components["schemas"]["CanonicalQuantity"];
            packageCount: number;
            coveredQuantity: components["schemas"]["CanonicalQuantity"];
            lineTotal: number;
            currencyCode: string;
        };
        /** @enum {string} */
        BasketItemResolutionStatus: "FULFILLED" | "AVAILABILITY_UNKNOWN" | "UNMATCHED" | "AMBIGUOUS" | "UNAVAILABLE" | "PACKAGE_QUANTITY_UNKNOWN" | "QUANTITY_UNIT_MISMATCH";
        InvalidComparisonPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-comparison-preview";
            /** @constant */
            title: "Invalid comparison preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_COMPARISON_PREVIEW";
            errors: components["schemas"]["ComparisonPreviewValidationError"][];
        };
        ComparisonPreviewValidationError: {
            field: string;
            message: string;
        };
        InvalidRecipeShoppingPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-recipe-shopping-preview";
            /** @constant */
            title: "Invalid recipe shopping preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_RECIPE_SHOPPING_PREVIEW";
            errors: components["schemas"]["RecipeShoppingPreviewValidationError"][];
        };
        RecipeShoppingPreviewValidationError: {
            field: string;
            message: string;
        };
        InvalidRecipeComparisonPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-recipe-comparison-preview";
            /** @constant */
            title: "Invalid recipe comparison preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_RECIPE_COMPARISON_PREVIEW";
            errors: components["schemas"]["RecipeComparisonPreviewValidationError"][];
        };
        RecipeComparisonPreviewValidationError: {
            field: string;
            message: string;
        };
        WeeklyPlanShoppingPreviewRequest: {
            occurrences: components["schemas"]["WeeklyPlanShoppingPreviewOccurrenceInput"][];
        };
        WeeklyPlanPantryShoppingPreviewRequest: {
            weeklyPlan: components["schemas"]["WeeklyPlanShoppingPreviewRequest"];
            pantry: components["schemas"]["WeeklyPlanPantryItemInput"][];
        };
        WeeklyPlanPantryItemInput: {
            requirement: string;
            quantity: components["schemas"]["WeeklyPlanPantryQuantityInput"];
        };
        WeeklyPlanPantryQuantityInput: {
            amount: number;
            unit: components["schemas"]["QuantityInputUnit"];
        };
        WeeklyPlanShoppingPreviewOccurrenceInput: {
            day: components["schemas"]["WeeklyPlanDay"];
            targetServings: number;
            recipe: components["schemas"]["WeeklyPlanShoppingPreviewRecipeInput"];
        };
        WeeklyPlanShoppingPreviewRecipeInput: {
            title: string;
            baseServings: number;
            ingredients: components["schemas"]["RecipeShoppingPreviewIngredientInput"][];
        };
        /** @enum {string} */
        WeeklyPlanDay: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
        WeeklyPlanShoppingPreviewResponse: {
            weeklyPlan: components["schemas"]["WeeklyPlanShoppingPreviewPlan"];
            shoppingList: components["schemas"]["WeeklyPlanShoppingPreviewShoppingList"];
        };
        WeeklyPlanPantryShoppingPreview: {
            weeklyPlan: components["schemas"]["WeeklyPlanShoppingPreviewPlan"];
            originalShoppingList: components["schemas"]["WeeklyPlanShoppingPreviewShoppingList"];
            pantryAdjustments: components["schemas"]["WeeklyPlanPantryAdjustmentEvidence"][];
            remainingShoppingList: components["schemas"]["WeeklyPlanPantryRemainingShoppingList"];
        };
        WeeklyPlanPantryAdjustmentEvidence: {
            /** Format: uuid */
            itemId: string;
            requirement: string;
            required: components["schemas"]["CanonicalQuantity"];
            pantryUsed?: components["schemas"]["CanonicalQuantity"];
            remaining?: components["schemas"]["CanonicalQuantity"];
            status: components["schemas"]["PantryAdjustmentStatus"];
        };
        /** @enum {string} */
        PantryAdjustmentStatus: "UNCHANGED" | "PARTIALLY_COVERED" | "FULLY_COVERED";
        WeeklyPlanPantryRemainingShoppingList: {
            /** Format: uuid */
            id: string;
            items: components["schemas"]["WeeklyPlanShoppingPreviewShoppingItem"][];
        };
        WeeklyPlanComparisonPreview: {
            weeklyPlanShoppingPreview: components["schemas"]["WeeklyPlanShoppingPreviewResponse"];
            comparisonPreview: components["schemas"]["ComparisonPreviewResponse"];
        };
        WeeklyPlanShoppingPreviewPlan: {
            /** Format: uuid */
            id: string;
            occurrences: components["schemas"]["WeeklyPlanShoppingPreviewOccurrence"][];
        };
        WeeklyPlanShoppingPreviewOccurrence: {
            /** Format: uuid */
            id: string;
            day: components["schemas"]["WeeklyPlanDay"];
            targetServings: number;
            recipe: components["schemas"]["WeeklyPlanShoppingPreviewRecipe"];
        };
        WeeklyPlanShoppingPreviewRecipe: {
            /** Format: uuid */
            id: string;
            title: string;
            baseServings: number;
            ingredients: components["schemas"]["WeeklyPlanShoppingPreviewIngredient"][];
        };
        WeeklyPlanShoppingPreviewIngredient: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
        };
        WeeklyPlanShoppingPreviewShoppingList: {
            /** Format: uuid */
            id: string;
            items: components["schemas"]["WeeklyPlanShoppingPreviewShoppingItem"][];
        };
        WeeklyPlanShoppingPreviewShoppingItem: {
            /** Format: uuid */
            id: string;
            requirement: string;
            quantity: components["schemas"]["CanonicalQuantity"];
            sources: components["schemas"]["WeeklyPlanShoppingPreviewSource"][];
        };
        WeeklyPlanShoppingPreviewSource: {
            /** Format: uuid */
            occurrenceId: string;
            /** Format: uuid */
            recipeId: string;
            /** Format: uuid */
            recipeIngredientId: string;
        };
        InvalidWeeklyPlanShoppingPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-weekly-plan-shopping-preview";
            /** @constant */
            title: "Invalid weekly plan shopping preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_WEEKLY_PLAN_SHOPPING_PREVIEW";
            errors: components["schemas"]["WeeklyPlanShoppingPreviewValidationError"][];
        };
        WeeklyPlanShoppingPreviewValidationError: {
            field: string;
            message: string;
        };
        InvalidWeeklyPlanPantryShoppingPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-weekly-plan-pantry-shopping-preview";
            /** @constant */
            title: "Invalid weekly plan pantry shopping preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_WEEKLY_PLAN_PANTRY_SHOPPING_PREVIEW";
            errors: components["schemas"]["WeeklyPlanPantryShoppingPreviewValidationError"][];
        };
        WeeklyPlanPantryShoppingPreviewValidationError: {
            field: string;
            message: string;
        };
        InvalidWeeklyPlanComparisonPreviewProblem: {
            /** @constant */
            type: "https://zakup-gotov.dev/problems/invalid-weekly-plan-comparison-preview";
            /** @constant */
            title: "Invalid weekly plan comparison preview request";
            /** @constant */
            status: 400;
            /** @constant */
            code: "INVALID_WEEKLY_PLAN_COMPARISON_PREVIEW";
            errors: components["schemas"]["WeeklyPlanComparisonPreviewValidationError"][];
        };
        WeeklyPlanComparisonPreviewValidationError: {
            field: string;
            message: string;
        };
        /** @enum {string} */
        RetailerId: "pyaterochka" | "perekrestok" | "chizhik" | "magnit" | "lenta" | "vkusvill" | "ozon-fresh" | "samokat";
        /** @enum {string} */
        RetailerCoverageStatus: "CONNECTED" | "DISCOVERY" | "DEGRADED" | "BLOCKED";
        /** @enum {string} */
        RetailerProductionAccessStatus: "READY" | "PENDING" | "BLOCKED";
        /** @enum {string} */
        RetailerComparisonStatus: "READY" | "UNCERTAIN" | "INCOMPLETE" | "UNAVAILABLE";
        /** @enum {string} */
        RetailerComparisonReason: "COVERAGE_DISCOVERY" | "COVERAGE_DEGRADED" | "COVERAGE_BLOCKED" | "PRODUCTION_ACCESS_PENDING" | "PRODUCTION_ACCESS_BLOCKED" | "DATA_NOT_AVAILABLE" | "SOURCE_UNAVAILABLE" | "ITEM_UNMATCHED" | "ITEM_AMBIGUOUS" | "ITEM_UNAVAILABLE" | "PACKAGE_QUANTITY_UNKNOWN" | "QUANTITY_UNIT_MISMATCH" | "AVAILABILITY_UNKNOWN";
        BasketTotal: {
            amount: number;
            currencyCode: string;
        };
        RetailerFreshness: {
            basis: components["schemas"]["RetailerFreshnessBasis"];
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            providerUpdatedAt?: string;
        };
        /** @enum {string} */
        RetailerFreshnessBasis: "OBSERVATION_ONLY" | "PROVIDER_TIMESTAMP";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API availability information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    getRetailerReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical retailer readiness information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerReadinessResponse"];
                };
            };
        };
    };
    createComparisonPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonPreviewRequest"];
            };
        };
        responses: {
            /** @description Product-safe comparison preview for all canonical retailers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonPreviewResponse"];
                };
            };
            /** @description Invalid comparison preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidComparisonPreviewProblem"];
                };
            };
        };
    };
    createRecipeShoppingPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeShoppingPreviewRequest"];
            };
        };
        responses: {
            /** @description Canonical Recipe to ShoppingList conversion preview with ingredient provenance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeShoppingPreviewResponse"];
                };
            };
            /** @description Invalid recipe shopping preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRecipeShoppingPreviewProblem"];
                };
            };
        };
    };
    createRecipeComparisonPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeComparisonPreviewRequest"];
            };
        };
        responses: {
            /** @description Composed recipe shopping and retailer comparison preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeComparisonPreviewResponse"];
                };
            };
            /** @description Invalid recipe comparison preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidRecipeComparisonPreviewProblem"] | components["schemas"]["InvalidRecipeShoppingPreviewProblem"] | components["schemas"]["InvalidComparisonPreviewProblem"];
                };
            };
        };
    };
    createWeeklyPlanShoppingPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyPlanShoppingPreviewRequest"];
            };
        };
        responses: {
            /** @description Canonical WeeklyPlan shopping preview with self-contained occurrence and Recipe provenance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPlanShoppingPreviewResponse"];
                };
            };
            /** @description Invalid weekly plan shopping preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidWeeklyPlanShoppingPreviewProblem"];
                };
            };
        };
    };
    createWeeklyPlanPantryShoppingPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyPlanPantryShoppingPreviewRequest"];
            };
        };
        responses: {
            /** @description Original WeeklyPlan shopping projection, Pantry adjustment evidence and remaining shopping projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPlanPantryShoppingPreview"];
                };
            };
            /** @description Invalid Pantry-aware weekly plan shopping preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidWeeklyPlanPantryShoppingPreviewProblem"];
                };
            };
        };
    };
    createWeeklyPlanComparisonPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyPlanComparisonPreviewRequest"];
            };
        };
        responses: {
            /** @description Composed WeeklyPlan shopping and retailer comparison preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPlanComparisonPreview"];
                };
            };
            /** @description Invalid weekly plan comparison preview request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidWeeklyPlanComparisonPreviewProblem"] | components["schemas"]["InvalidWeeklyPlanShoppingPreviewProblem"] | components["schemas"]["InvalidComparisonPreviewProblem"];
                };
            };
        };
    };
}
